### ISSUE TITLE
Queue handling fails for Mailman3 web pages in Non-English locales

### ISSUE THREAD

**Issue by alexbarton** [u1f35c/listadmin3#1]
When Mailman3 uses a Non-English locale for its webpages, listadmin3 fails when handling queued messages:

```
fetching data for <redacted> ...
Traceback (most recent call last):
  File "/usr/local/src/listadmin3/listadmin3.git/./listadmin3", line 421, in <module>
    listadmin3()
  File "/usr/local/src/listadmin3/listadmin3.git/./listadmin3", line 417, in listadmin3
    moderate_list(webui, l)
  File "/usr/local/src/listadmin3/listadmin3.git/./listadmin3", line 383, in moderate_list
    did_msgs = moderate_messages(mmui, listname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/src/listadmin3/listadmin3.git/./listadmin3", line 274, in moderate_messages
    msgs = mmui.get_held_messages(listname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/src/listadmin3/listadmin3.git/./listadmin3", line 111, in get_held_messages
    msg_form = self._fetch_held_messages(listname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/src/listadmin3/listadmin3.git/./listadmin3", line 105, in _fetch_held_messages
    raise HTMLParseError("Couldn't find held message list")
HTMLParseError: Couldn't find held message list
```

This is because of this code in https://github.com/u1f35c/listadmin3/blob/main/listadmin3#L103-L104, which explicitly looks for the English message:

```python
        if msg_form.text.strip() != "Held Messages":
            raise HTMLParseError("Couldn't find held message list")
```

Not sure what the best solution is, basically this is only an additional test that the correct page was returned. So I guess there are (at least) two options:

1. get rid of this test altogether
2. test for all possible languages

For German, this could look like this:

```python
        if msg_form.text.strip() not in [
            "Held Messages", # en_US
            "Zurückgehaltene Nachrichten", # de_DE
        ]:
            raise HTMLParseError("Couldn't find held message list")
```

Both "solutions" work in my tests. What do you think? Most probably (1) is much easier to maintain, although (2) is safer?

**Comment by alexbarton** [comment]
I started to implement option (2), having a list with all possible translated strings, here:
https://github.com/u1f35c/listadmin3/compare/main...alexbarton:listadmin3:bug1-NonEnglist-List?expand=1

But I don't think this scales well … ;)

So probably consider my pull request #2, removing this check altogether, which solves this issue for me as well.

**Comment by u1f35c** [comment]
OOI, for the German case does the page have `<html lang="de">` at the start? I wonder about doing _some_ checks when we know the language, and falling back to just accepting if we get a language that hasn't got a specific exclusion? Though TBH I think your PR is probably safe enough; this is for information we're returning to the user so if we get the wrong thing it should be obvious.

**Comment by alexbarton** [comment]
Hm … good point … but even wors:

The German web page still has `<html lang="en">` in it – oh my!
